# Конфигурация сервиса для pricing-service
server:
  port: 8082

spring:
  application:
    name: pricing-service
  datasource:
    url: jdbc:postgresql://postgres-pricing:5432/pricing_db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true

# ?????????? ?????????
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ??????????? Circuit Breaker ?????????
resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 15000

feign:
  client:
    config:
      catalog-service:
        connectTimeout: 2000
        readTimeout: 3000