# ????????? ?????? ??? pricing-service (??????????)
server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://postgres-pricing:5432/pricing_db
    username: admin
    password: root
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true
  # ????????? ??????????? ??????????
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

# ?????????? ?????????
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# ??????????? Circuit Breaker ?????????
resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 15000

feign:
  client:
    config:
      catalog-service:
        connectTimeout: 2000
        readTimeout: 3000