# Конфигурация сервиса для order-service
server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://postgres-order:5432/order_db
    username: admin
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog-master.yml
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
  instance:
    prefer-ip-address: true

# ????????? Feign ???????? ??? order-service
feign:
  client:
    config:
      catalog-service:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: full
      pricing-service:
        connectTimeout: 3000
        readTimeout: 5000
        loggerLevel: full

# ????? ??????????? Circuit Breaker ????????? ??? order-service
resilience4j:
  circuitbreaker:
    instances:
      catalogService:
        slidingWindowSize: 5
        failureRateThreshold: 40  # ????? ??????????????
        waitDurationInOpenState: 30000
      pricingService:
        slidingWindowSize: 5
        failureRateThreshold: 40
        waitDurationInOpenState: 30000
  retry:
    instances:
      catalogService:
        maxAttempts: 3
        waitDuration: 1000