spring.application.name=tobacco_shop

spring.liquibase.enabled=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/tobacco
spring.datasource.username=admin
spring.datasource.password=root